### ISSUE TITLE
Persist Server State Before Responding to RPCs

### ISSUE THREAD

**Issue by wjdix** [dev-urandom/graft#13]
![screen shot 2013-08-28 at 8 44 35 pm](https://f.cloud.github.com/assets/39646/1046849/9582c946-104c-11e3-8e3f-167a5b1765a3.png)

**Comment by benmills** [comment]
Are you talking about disk persistance? I feel like we can punt on that until we have the core system working. I do wonder what we should do here. Just write JSON to a flat file? Maybe we should see what go-raft does.

**Comment by wjdix** [comment]
Given that persisting certain data is a requirement before handling any RPCs, I don't think we can push this off quite as long. WHen you merge https://github.com/dev-urandom/graft/pull/12 this will pretty much be done. Error handling is sht, but so it goes.
